trigger:
    - master
    - release/*

variables:
    - name: artifactName
      value: 'Luminis.AzureActiveDirectory'
    - name: nugetArtifactName
      value: 'Luminis.AzureActiveDirectory.Nuget'
    - name: buildConfiguration
      value: 'Release'

stages:
    - stage: Build
      jobs:
          - job: Build
            displayName: Build Nextpipelab.Library
            pool:
                vmImage: 'ubuntu-18.04'

            steps:
                - task: GitVersion@5
                  displayName: Determine version
                  inputs:
                      additionalArguments: '/output buildserver'
                      configFilePath: 'GitVersion.yml'

                - bash: export
                  displayName: Log all environment vars

                - task: DotNetCoreCLI@2
                  displayName: DotnetCore Build
                  inputs:
                      publishWebProjects: false
                      command: build
                      projects: AzureActiveDirectory.sln
                      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:version=$(GitVersion.FullSemVer)'
                      versioningScheme: byBuildNumber

                - task: DotNetCoreCLI@2
                  displayName: DotnetCore Test
                  inputs:
                      command: test
                      projects: '**/*Test/*.csproj'
                      arguments: '--collect:"Code Coverage"'

                - task: PublishBuildArtifacts@1
                  displayName: publish build artifacts
                  inputs: 
                    pathtoPublish: $(Build.ArtifactStagingDirectory)
                    artifactName: $(artifactName)

                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs: 
                    command: push
                    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
                    nuGetFeedType: external 
                    publishFeedCredentials: PublicNugetServiceConnection